server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/syssbglxt?serverTimezone=GMT%2b8
    username: root
    password: mumiaosen123
  redis:
    host: localhost
    port: 6379
    password: mumiaosen123
    database: 0
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    protocol: smtps
#    protocol: smtp
    # 配置 SMTP 服务器地址
    host: smtp.163.com
    # 发送者邮箱
    # 发送者邮箱
    #  端口587只应用于提交（即，邮件客户端到邮件服务器）
    #  端口25只应用于中继（即，邮件服务器到邮件服务器通信）
    #  SMTP中，为加密连接选择的端口是465。
    #    username: 19935441736@163.com
    username: 19935441736@163.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: KGKQRECTTWFSLKMP
    # 端口号465或587
#    port: 465
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8



mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


files:
  upload:
    path: D:/Java/syssbglxt-upload/



